sudo: required

language: java

os:
  - linux

services:
  - mysql

branches:
  only:
    - master
    - /^(dev)|(dev_.*)$/

before_script:
  - mysqladmin -u root password "123456"
  - python initDB.py

script:
  - mvn test
